### ISSUE TITLE
Couchbase Package not available 

### ISSUE THREAD

**Issue by splybon** [disney/couchbase#78]
Running into an issue where the release packages are giving me a 403 forbidden error, you can see for yourself here:

http://packages.couchbase.com/releases/3.0.0/couchbase-server-community_3.0.0-ubuntu14.04_amd64.deb

Is there anywhere else we to get the community edition?  I've tried earlier versions and it seems like they have the same issue.

**Comment by haidangwa** [comment]
couchbase no longer maintains versions older than 3.0.1. 
https://www.couchbase.com/downloads
